# version: '3.8'

# services:
#   dev:
#     container_name: payfund_api_dev
#     image: payfund-api-dev:1.0.0
#     ports:
#       - 6754:6754
#     networks:
#       - postgres
#     volumes:
#       - /var/folders/postgres:/data/postgres
#   prod:
#     container_name: payfund_api_prod
#     image: payfund-api-prod:1.0.0
#     ports:
#       - 3990:3990
#     networks:
#       - postgres
#     volumes:
#       - /var/folders/pgadmin:/root/.pgadmin
# networks:
#   postgres:


# version: '3'
# services:
#   postgres:
#     container_name: payfund_api_dev
#     image: payfund_api_dev
#     ports:
#       - '6754:6754'
#     volumes:
#       - /var/folders/payfund_api_dev:/data/payfund_api_dev
#     env_file:
#       - docker.env
#     networks:
#       - postgres

#   pgadmin:
#     links:
#       - postgres:postgres
#     container_name: payfund_api_prod
#     image: payfund_api_prod
#     ports:
#       - '6060:60'
#     volumes:
#       - /var/folders/payfund_api_prod:/root/.payfund_api_prod
#     env_file:
#       - docker.env
#     networks:
#       - postgres

# networks:
#   postgres:
#     driver: bridge



version: '3'
services:
  postgres:
    container_name: payfund_api_dev
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /var/folders/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: payfund_api_prod
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /var/folders/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
